spring:
  application:
    name: Payment Service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI}
  mongodb:
    uri: mongodb://localhost:27017/test

server:
  port: 8080

swagger-ui:
  oauth:
    issuer-uri: ${OAUTH_ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: "*"