spring:
  application:
    name: Payment Service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI}
      client:
        registration:
          service-account:
            client-id: ${PAYMENT_SERVICE_CLIENT_ID}
            client-secret: ${PAYMENT_SERVICE_CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          service-account:
            token-uri: ${OAUTH_ISSUER_URI}/protocol/openid-connect/token


  mongodb:
    uri: mongodb://localhost:27017/test

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer



server:
  port: 8080

swagger-ui:
  oauth:
    issuer-uri: ${OAUTH_ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.intern.paymentservice: DEBUG